// Code generated by logcopter-gen; DO NOT EDIT.

package server

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-datadrop.pkg.server")
