import type { Table } from "../model/table";

import batchesJson from "./batches.json";
import censusJson from "./census.json";
import readingsJson from "./readings.json";

/**
 * Deterministic tables for stories and tests.
 *
 * Committed JSON, regenerated by `bun run fixtures`. Stories read these rather
 * than calling the generator, so a story never fails because of the generator
 * and a screenshot diff is never seeded noise.
 *
 * Each is a complete `Table` as pkg/tabular emits one. The casts are safe
 * because make-fixtures.ts builds them from the same `Table` type; JSON module
 * imports simply widen the literal types on the way through.
 */

/** A stream: envelope columns plus payload, four stations over six hours. */
export const readings = readingsJson as unknown as Table;

/** A dataset with a schema, and the zero-padded id a sniffer would destroy. */
export const census = censusJson as unknown as Table;

/** A truncated dataset — the state the truncation notice exists for. */
export const batches = batchesJson as unknown as Table;

export const FIXTURES = { readings, census, batches } as const;

// Chart specifications and plots, built by the real engine (DATADROP-6
// follow-up). Separate module so a story importing a plot does not pull in the
// whole fixture set.
export { READINGS, step, chartSpec, autoSpec, chartPlot, pipelineOf } from "./charts";
