import { describe, expect, test } from "bun:test";
import {
  initialLayout,
  layoutSlice,
  leaf,
  spacesOfStage,
  split,
  type LayoutState,
  type Stage,
  type StageId,
  type Workspace,
} from "../src/store/layout";
import { validate, migrate } from "../src/store/persist";
import {
  ACCOUNT_SPACE_ID,
  ACCOUNT_STAGE_ID,
  defaultLayout,
  mergeStages,
  pinnedStages,
  SIGNIN_SPACE_ID,
  SIGNIN_STAGE_ID,
  singleStageLayout,
  TOUR_SPACE_IDS,
  WELCOME_STAGE_ID,
  WORK_STAGE_ID,
} from "../src/store/stages";
import { intersectScopes } from "../src/appkit/AppScope";
import v1Payload from "./fixtures/persisted-v1.json";

/**
 * Stages: the layer above workspaces (DATADROP-8 DR-58 … DR-61, DR-73).
 *
 * Three things here are worth more than the rest and are the reason the file
 * exists:
 *
 *  - the **space-pointer invariant**, which walks every reducer in the slice.
 *    A mirrored field is a correctness hazard that grows with every new
 *    reducer, and the honest way to carry one is to make the twelfth reducer
 *    that forgets fail loudly (DR-60).
 *  - the **migration**, against a version-1 payload produced by the version-1
 *    source itself. The fixture in `test/fixtures/persisted-v1.json` was
 *    generated by running `defaultSpaces()` out of commit f53be15 — the last
 *    commit before this ticket — rather than hand-written, so it is what a real
 *    browser held rather than what someone remembered it holding.
 *  - **scope composition**, including the empty intersection, which is the case
 *    that renders a blank dropdown if `Tile`'s own-application rule is ever
 *    dropped.
 */

const layout = layoutSlice.reducer;

/* --------------------------------------------------- the pinned stages -- */

describe("the pinned stages", () => {
  test("there are four, all pinned, and the sign-in stage hides its chrome", () => {
    const { stages } = pinnedStages();
    expect(stages.map((s) => s.id)).toEqual([
      SIGNIN_STAGE_ID,
      WELCOME_STAGE_ID,
      ACCOUNT_STAGE_ID,
      WORK_STAGE_ID,
    ]);
    expect(stages.every((s) => s.pinned)).toBe(true);

    const signin = stages.find((s) => s.id === SIGNIN_STAGE_ID) as Stage;
    // A visitor who is not signed in must not be offered a switcher to a stage
    // whose every tile would show 401.
    expect(signin.chrome.stageBar).toBe(false);
    expect(signin.chrome.workspaces).toBe(false);
    expect(signin.apps).toEqual(["signin", "about"]);
  });

  test("work is the only stage with no allow-list", () => {
    const withoutScope = pinnedStages().stages.filter((s) => s.apps === null);
    expect(withoutScope.map((s) => s.id)).toEqual([WORK_STAGE_ID]);
  });

  test("every pinned workspace names a stage that exists", () => {
    const { stages, spaces } = pinnedStages();
    const ids = new Set(stages.map((s) => s.id));
    expect(spaces.filter((s) => !ids.has(s.stageId))).toEqual([]);
  });

  test("the default layout lands on work, on a workspace that exists", () => {
    const state = defaultLayout();
    expect(state.currentStageId).toBe(WORK_STAGE_ID);
    const space = state.spaces.find((s) => s.id === state.currentSpaceId);
    expect(space?.stageId).toBe(WORK_STAGE_ID);
    expect(space?.name).toBe("build");
    // The work stage owns no pinned workspaces: they are a starting point the
    // user owns, renameable and deletable.
    expect(spacesOfStage(state, WORK_STAGE_ID).every((s) => !s.pinned)).toBe(true);
  });

  test("no two stores agree on a workspace id that is not code-defined", () => {
    // The same property `test/instances.test.ts` states for whole stores,
    // asserted here at the source: a fixed id on an UNPINNED workspace would
    // make two independent layouts collide, and `work`'s opening `build` space
    // is the one that nearly was one.
    const a = defaultLayout();
    const b = defaultLayout();
    const bIds = new Set(b.spaces.map((s) => s.id));
    const shared = a.spaces.filter((s) => bIds.has(s.id));
    expect(shared.every((s) => s.pinned)).toBe(true);
  });
});

/* ----------------------------------------- the mirrored space pointer -- */

describe("the space pointer never desynchronises", () => {
  /** A layout with two stages and two workspaces each, so every guard is live. */
  function twoStages(): LayoutState {
    const stage = (id: StageId, name: string): Stage => ({
      id,
      name,
      apps: null,
      chrome: { masthead: true, workspaces: true, stageBar: true },
      currentSpaceId: `${id}-a`,
    });
    const space = (id: string, stageId: StageId): Workspace => ({
      id,
      name: id,
      stageId,
      tree: split("row", leaf("chart"), leaf("table")),
    });
    return {
      stages: [stage("s1", "one"), stage("s2", "two")],
      currentStageId: "s1",
      spaces: [space("s1-a", "s1"), space("s1-b", "s1"), space("s2-a", "s2"), space("s2-b", "s2")],
      currentSpaceId: "s1-a",
    };
  }

  /**
   * A representative payload per reducer.
   *
   * Undefined means "call it with no argument". A reducer added without an
   * entry here fails the coverage test below rather than being silently
   * skipped, which is the failure mode a table like this usually has.
   */
  const PAYLOADS: Record<string, unknown> = {
    setRatio: { nodeId: "n", ratio: 0.4 },
    splitLeaf: { nodeId: "n", dir: "row" },
    closeLeaf: "n",
    setLeafApp: { nodeId: "n", app: "trace" },
    setLeafDoc: { nodeId: "n", docId: null },
    renameLeaf: { nodeId: "n", label: "mine" },
    duplicateLeaf: "n",
    beginRename: "s1-a",
    openImport: { target: { kind: "stage" }, prefill: "", from: null },
    closeImport: undefined,
    showNotice: { ok: true, title: "Copied", body: "…" },
    dismissNotice: undefined,
    replaceLeafFromBundle: {
      nodeId: "n",
      leaf: { id: "x", type: "leaf", app: "chart", docId: null },
    },
    insertWorkspaceFromBundle: {
      space: {
        id: "fresh",
        name: "fresh",
        stageId: "s1",
        tree: { id: "t", type: "leaf", app: "chart", docId: null },
      },
    },
    insertStageFromBundle: {
      stage: {
        id: "s3",
        name: "imported",
        apps: null,
        chrome: { masthead: true, workspaces: true, stageBar: true },
        currentSpaceId: "",
      },
      spaces: [
        {
          id: "s3-a",
          name: "a",
          stageId: "s3",
          tree: { id: "t2", type: "leaf", app: "chart", docId: null },
        },
      ],
    },
    swapTiles: { a: "n1", b: "n2" },
    dockTile: { from: "n1", to: "n2", zone: "left" },
    addSpace: undefined,
    removeSpace: "s1-a",
    renameSpace: { spaceId: "s1-b", name: "renamed" },
    cloneSpace: "s1-a",
    setCurrentSpace: "s2-b",
    setSpaceApps: { spaceId: "s1-a", apps: ["chart"] },
    addStage: undefined,
    removeStage: "s2",
    renameStage: { stageId: "s2", name: "renamed" },
    setCurrentStage: "s2",
    moveSpaceToStage: { spaceId: "s1-b", stageId: "s2" },
    replaceLayout: undefined,
  };

  test("every reducer in the slice has a representative payload here", () => {
    // Without this the invariant test below passes trivially for any reducer
    // someone adds and forgets to exercise.
    const missing = Object.keys(layoutSlice.actions).filter((name) => !(name in PAYLOADS));
    expect(missing).toEqual([]);
  });

  test("every reducer leaves the space pointer consistent", () => {
    const failures: string[] = [];
    for (const [name, actionCreator] of Object.entries(layoutSlice.actions)) {
      const before = twoStages();
      const payload = PAYLOADS[name];
      const action =
        name === "replaceLayout"
          ? layoutSlice.actions.replaceLayout(twoStages())
          : name === "addSpace"
            ? layoutSlice.actions.addSpace("fresh")
            : name === "addStage"
              ? layoutSlice.actions.addStage("fresh")
              : (actionCreator as (p: unknown) => { type: string })(payload);

      const after = layout(before, action as never);
      const stage = after.stages.find((s) => s.id === after.currentStageId);
      if (!stage) {
        failures.push(`${name}: currentStageId names no stage`);
        continue;
      }
      if (after.currentSpaceId !== stage.currentSpaceId) {
        failures.push(
          `${name} desynchronised the pointer: layout ${after.currentSpaceId}, ` +
            `stage ${stage.currentSpaceId}`,
        );
      }
    }
    expect(failures).toEqual([]);
  });

  test("switching stages remembers each stage's workspace", () => {
    // The failure DR-60 exists to prevent: you are on `gallery` in `work`, you
    // switch to `account` to mint a token, you switch back, and you are on
    // `build` because there was one global pointer.
    let state = twoStages();
    state = layout(state, layoutSlice.actions.setCurrentSpace("s1-b"));
    state = layout(state, layoutSlice.actions.setCurrentStage("s2"));
    expect(state.currentSpaceId).toBe("s2-a");
    state = layout(state, layoutSlice.actions.setCurrentStage("s1"));
    expect(state.currentSpaceId).toBe("s1-b");
  });

  test("switching to a workspace in another stage switches the stage too", () => {
    const state = layout(twoStages(), layoutSlice.actions.setCurrentSpace("s2-b"));
    expect(state.currentStageId).toBe("s2");
    expect(state.currentSpaceId).toBe("s2-b");
  });
});

/* ---------------------------------------------------------- the guards -- */

describe("deletion keeps the same guard at every level", () => {
  test("removeSpace counts within the STAGE, not the layout", () => {
    // The old guard was `state.spaces.length < 2`, which under stages is wrong
    // in the permissive direction: a stage holding one workspace inside a
    // layout holding twelve would let you delete it, leaving a stage whose
    // canvas is empty with no way back (DR-72).
    const state: LayoutState = {
      stages: [
        {
          id: "s1",
          name: "one",
          apps: null,
          chrome: { masthead: true, workspaces: true, stageBar: true },
          currentSpaceId: "only",
        },
      ],
      currentStageId: "s1",
      spaces: [
        { id: "only", name: "only", stageId: "s1", tree: leaf("chart") },
        { id: "elsewhere", name: "elsewhere", stageId: "s2", tree: leaf("chart") },
      ],
      currentSpaceId: "only",
    };
    const after = layout(state, layoutSlice.actions.removeSpace("only"));
    expect(after.spaces.map((s) => s.id)).toContain("only");
  });

  test("a pinned workspace refuses removal and rename", () => {
    const state = defaultLayout();
    const removed = layout(state, layoutSlice.actions.removeSpace(ACCOUNT_SPACE_ID));
    expect(removed.spaces.some((s) => s.id === ACCOUNT_SPACE_ID)).toBe(true);
    const renamed = layout(
      state,
      layoutSlice.actions.renameSpace({ spaceId: ACCOUNT_SPACE_ID, name: "mine" }),
    );
    expect(renamed.spaces.find((s) => s.id === ACCOUNT_SPACE_ID)?.name).toBe("profile");
  });

  test("a pinned stage refuses removeStage and renameStage", () => {
    const state = defaultLayout();
    const removed = layout(state, layoutSlice.actions.removeStage(ACCOUNT_STAGE_ID));
    expect(removed.stages.some((s) => s.id === ACCOUNT_STAGE_ID)).toBe(true);
    const renamed = layout(
      state,
      layoutSlice.actions.renameStage({ stageId: ACCOUNT_STAGE_ID, name: "mine" }),
    );
    expect(renamed.stages.find((s) => s.id === ACCOUNT_STAGE_ID)?.name).toBe("account");
  });

  test("a user stage can be added and removed, and takes its workspaces with it", () => {
    const added = layout(defaultLayout(), layoutSlice.actions.addStage("client demo"));
    const stage = added.stages.find((s) => s.name === "client demo") as Stage;
    expect(added.currentStageId).toBe(stage.id);
    expect(spacesOfStage(added, stage.id)).toHaveLength(1);

    const removed = layout(added, layoutSlice.actions.removeStage(stage.id));
    expect(removed.stages.some((s) => s.id === stage.id)).toBe(false);
    expect(spacesOfStage(removed, stage.id)).toHaveLength(0);
  });

  test("the last stage cannot be removed", () => {
    const one = initialLayout();
    const after = layout(one, layoutSlice.actions.removeStage(one.currentStageId));
    expect(after.stages).toHaveLength(1);
  });
});

/* ------------------------------------------------------------- scopes -- */

describe("application scope composes by intersection", () => {
  test("null contributes nothing", () => {
    expect(intersectScopes(null, null)).toBeNull();
    expect(intersectScopes(null, ["chart", "table"])).toEqual(["chart", "table"]);
  });

  test("most restrictive wins", () => {
    expect(intersectScopes(["chart", "table", "trace"], ["chart", "trace"], ["trace"])).toEqual([
      "trace",
    ]);
  });

  test("an empty intersection is legal and is the empty array, never null", () => {
    // A stage offering ["signin"] inside an instance offering ["chart"]. It
    // must not be confused with "no constraint", which would offer everything —
    // the exact inversion of what the composition was asked for.
    expect(intersectScopes(["chart"], ["signin"])).toEqual([]);
  });
});

/* ------------------------------------------------------- the migration -- */

describe("persisted layout version 1 → 2", () => {
  test("the fixture really is a version-1 payload with ten workspaces", () => {
    // Guards the fixture itself: a regenerated file that lost its shape would
    // otherwise make every assertion below vacuous.
    expect(v1Payload.version).toBe(1);
    expect(v1Payload.layout.spaces).toHaveLength(10);
    expect(v1Payload.layout.spaces.map((s) => s.name)).toContain("my cockpit");
  });

  test("every user workspace joins the work stage and none is lost", () => {
    const valid = validate(v1Payload);
    expect(valid).not.toBeNull();
    const work = spacesOfStage(valid!.layout, WORK_STAGE_ID);
    // Ten stored spaces, two of which were the v1 hardwired pair and are
    // dropped because mergeStages re-creates them as STAGES (DR-59).
    expect(work).toHaveLength(8);
    expect(work.map((s) => s.name)).toEqual([
      "my cockpit",
      "explore",
      "gallery",
      "1·objects",
      "2·pipeline",
      "3·encode",
      "4·docs",
      "help",
    ]);
  });

  test("the v1 hardwired pair is dropped rather than duplicated", () => {
    const valid = validate(v1Payload);
    const ids = valid!.layout.spaces.map((s) => s.id);
    expect(ids).not.toContain("ws-welcome");
    // `ws-account` comes back, but as the account STAGE's code-defined
    // workspace rather than as a workspace in `work`.
    expect(ids.filter((id) => id === ACCOUNT_SPACE_ID)).toHaveLength(1);
    expect(valid!.layout.spaces.find((s) => s.id === ACCOUNT_SPACE_ID)?.stageId).toBe(
      ACCOUNT_STAGE_ID,
    );
  });

  test("the four pinned stages appear, with their workspaces", () => {
    const valid = validate(v1Payload);
    const stages = valid!.layout.stages.map((s) => s.id);
    expect(stages).toContain(SIGNIN_STAGE_ID);
    expect(stages).toContain(WELCOME_STAGE_ID);
    expect(stages).toContain(ACCOUNT_STAGE_ID);
    expect(stages).toContain(WORK_STAGE_ID);
    const ids = valid!.layout.spaces.map((s) => s.id);
    expect(ids).toContain(SIGNIN_SPACE_ID);
    for (const id of TOUR_SPACE_IDS) expect(ids).toContain(id);
  });

  test("the world survives untouched", () => {
    const valid = validate(v1Payload);
    expect(Object.keys(valid!.world.docs)).toEqual(Object.keys(v1Payload.world.docs));
    expect(valid!.world.activeDocId).toBe(v1Payload.world.activeDocId);
  });

  test("migrate is idempotent on a version-2 payload", () => {
    // The failure mode: a second load re-wraps everything into a SECOND work
    // stage. It does not throw and no test fails unless this one exists.
    const once = migrate(v1Payload);
    const twice = migrate(once);
    expect(twice).toBe(once);
  });

  test("a version-3 payload is refused rather than half-understood", () => {
    expect(migrate({ ...v1Payload, version: 3 })).toBeNull();
    expect(validate({ ...v1Payload, version: 3 })).toBeNull();
  });
});

/* ------------------------------------------------------- mergeStages -- */

describe("mergeStages", () => {
  test("a workspace whose stage is gone joins work rather than vanishing", () => {
    const orphan: Workspace = {
      id: "orphan",
      name: "orphan",
      stageId: "gone",
      tree: leaf("chart"),
    };
    const { spaces } = mergeStages([], [orphan]);
    expect(spaces.find((s) => s.id === "orphan")?.stageId).toBe(WORK_STAGE_ID);
  });

  test("a stage with no workspaces at all gets one", () => {
    const { stages, spaces } = mergeStages([], []);
    for (const stage of stages) {
      const own = spaces.filter((s) => s.stageId === stage.id);
      expect(own.length).toBeGreaterThan(0);
      expect(own.some((s) => s.id === stage.currentSpaceId)).toBe(true);
    }
  });

  test("a pinned stage keeps its remembered workspace but not its definition", () => {
    const stored: Stage = {
      id: ACCOUNT_STAGE_ID,
      name: "renamed by a user",
      apps: ["chart"],
      chrome: { masthead: false, workspaces: false, stageBar: false },
      currentSpaceId: ACCOUNT_SPACE_ID,
    };
    const { stages } = mergeStages([stored], []);
    const account = stages.find((s) => s.id === ACCOUNT_STAGE_ID) as Stage;
    expect(account.name).toBe("account");
    expect(account.chrome.workspaces).toBe(true);
    expect(account.currentSpaceId).toBe(ACCOUNT_SPACE_ID);
  });
});

/* ------------------------------------------------- single-stage layouts -- */

describe("singleStageLayout", () => {
  test("mints a fresh stage id per call", () => {
    const a = singleStageLayout("build", leaf("chart"));
    const b = singleStageLayout("build", leaf("chart"));
    expect(a.currentStageId).not.toBe(b.currentStageId);
    expect(a.currentSpaceId).not.toBe(b.currentSpaceId);
  });

  test("offers no stage switcher, because there is nothing to switch to", () => {
    const one = singleStageLayout("build", leaf("chart"));
    expect(one.stages[0]?.chrome.stageBar).toBe(false);
  });
});
